import "./globals.css";
import { roboto } from "./ui/fonts";

export const metadata = {
  title: "Service",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
