import './globals.css'
import {roboto} from './ui/fonts'
import {Providers} from './lib/provider'

export const metadata = {
  title: 'Service',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
